// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "Plugin_Chooser_UI.H"

Fl_Menu_Item Plugin_Chooser_UI::menu_type_choice[] = {
 {"ALL", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"CLAP", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"LADSPA", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"LV2", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"VST2", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"VST3", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Plugin_Chooser_UI::Plugin_Chooser_UI(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
{ Fl_Group* o = new Fl_Group(10, 5, 155, 20);
  { all_button = new Fl_Round_Button(10, 5, 50, 20, "&All");
    all_button->type(102);
    all_button->shortcut(0x80061);
    all_button->down_box(FL_ROUND_DOWN_BOX);
    all_button->value(1);
  } // Fl_Round_Button* all_button
  { favorites_button = new Fl_Round_Button(65, 5, 100, 20, "&Favorites");
    favorites_button->type(102);
    favorites_button->shortcut(0x80066);
    favorites_button->down_box(FL_ROUND_DOWN_BOX);
  } // Fl_Round_Button* favorites_button
  o->end();
} // Fl_Group* o
{ Fl_Group* o = new Fl_Group(5, 29, 825, 77);
  o->box(FL_UP_FRAME);
  { name_input = new Fl_Input(75, 38, 300, 24, "Name:");
    name_input->labelsize(12);
    name_input->textsize(13);
  } // Fl_Input* name_input
  { author_input = new Fl_Input(435, 39, 210, 22, "Author:");
    author_input->labelsize(12);
    author_input->textsize(13);
  } // Fl_Input* author_input
  { outputs_input = new Fl_Value_Input(730, 70, 30, 24, "Outputs:");
    outputs_input->labelsize(12);
  } // Fl_Value_Input* outputs_input
  { inputs_input = new Fl_Value_Input(730, 39, 30, 24, "Inputs:");
    inputs_input->labelsize(12);
  } // Fl_Value_Input* inputs_input
  { category_choice = new Fl_Choice(75, 70, 405, 24, "Category:");
    category_choice->down_box(FL_BORDER_BOX);
    category_choice->labelsize(12);
    category_choice->textsize(12);
  } // Fl_Choice* category_choice
  o->resizable(0);
  o->end();
} // Fl_Group* o
{ table_group = new Fl_Group(5, 115, 725, 380);
  { table = new Fl_Table(5, 115, 725, 380);
    table->end();
    Fl_Group::current()->resizable(table);
  } // Fl_Table* table
  table_group->end();
  Fl_Group::current()->resizable(table_group);
} // Fl_Group* table_group
{ type_choice = new Fl_Choice(475, 70, 95, 24, "Type:");
  type_choice->down_box(FL_BORDER_BOX);
  type_choice->labelsize(12);
  type_choice->textsize(12);
  type_choice->menu(menu_type_choice);
} // Fl_Choice* type_choice
end();
}
